version: '3'
name: rcdoc-back-test

services:
  backend:
    build:
      context: .
      target: final
    ports:
      - 80:8080
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    links:
      - redis
      - postgres
    env_file:
      - ./test_env/backend.properties

  redis:
    # This will change to valkey soon(tm)
    image: "redis:7.2.4-alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:  
      - "./test_config/redis:/usr/local/etc/redis:ro"
  
  postgres:
    restart: always
    image: "postgres:alpine"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 10

    volumes:
      - "pg_data:/var/lib/postgresql/data"
    env_file:
      - ./test_env/postgres.properties
    user: postgres

volumes:
  pg_data: {}

